version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"    # Expose Uvicorn to port 8000 (though it's proxied by Nginx)
    volumes:
      - .:/app         # Mount the current directory to /app inside the container
    depends_on:
      - nginx
    networks:
      - fastapi_network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - fastapi_network
    ports:
      - "81:81"

networks:
  fastapi_network:
    driver: bridge
